eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('product.urls', namespace='product')),
     path('pos/', include('pos.urls', namespace='pos')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from . import views


app_name = 'pos'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/increment/<int:item_id>/',
         views.increment_cart_item, name='increment_cart_item'),
    path('cart/decrement/<int:item_id>/',
         views.decrement_cart_item, name='decrement_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart_item/<int:item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('sales/', views.sales, name='sales'),
    path('sale/<int:sale_id>/', views.sale, name='sale'),
    path('sales_h/', views.sales_h, name='sales_h'),
    path('toggle_vat/', views.toggle_add_vat, name='toggle_vat'),
    path('update_discount/', views.update_discount, name='update_discount'),
    path('eshop/inventory/', views.menu, name='menu'),
    path('eshop/expiring/', views.expiring, name='expiring'),
    path('eshop/receivings/', views.receivings, name='received'),
    path('eshop/supplies/', views.supplies, name='supplies'),
    path('eshop/about/', views.about, name='about'),
    path('eshop/cataloque/', views.cataloque, name='cataloque'),
    path('cataloque/<int:cataloque_id>/',
         views.cataloque_detail, name='cataloque_detail'),
    path('export_cataloque/<int:cataloque_id>/',
         views.export_cataloque, name='export_cataloque'),
    path('eshop/mails/', views.mails, name='mails'),
    path('eshop/create_mails/', views.create_mail, name='create_mails'),
    path('eshop/cashup/', views.cashup, name='cashup'),
    path('eshop/cashups/', views.cashups, name='cashups'),
    path('cashup/<int:cashup_id>/',
         views.cashup_detail, name='cashup_detail'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('create_product/', views.create_product, name='create_product'),
    path('create_category/', views.create_category, name='create_category'),
    path('products/', views.products, name='products'),
    path('edit_category/<int:category_id>/',
         views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/',
         views.delete_category, name='delete_category'),
    path('edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    # Delete Product
    path('delete_product/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('stock/', views.stock, name='stock'),
    path('low_stock/', views.low_stock, name='low_stock'),
    path('out_of_stock/', views.out_of_stock, name='out_of_stock'),
    path('create_stock_take/', views.create_stock_take, name='create_stock_take'),
    path('stocks/', views.stocks, name='stocks'),
    path('stock_detail/<int:stock_take_id>/',
         views.stock_detail, name='stock_detail'),
    path('stock_take/<int:stock_take_id>/update/<int:stock_take_item_id>/',
         views.update_stock_take_item, name='update_stock'),
    path('stockmovement/', views.stock_movement, name='stock_movement'),
    path('suppliers/', views.suppliers, name='suppliers'),
    path('supplier_create/', views.supplier_create, name='supplier_create'),
    path('receivings/', views.receivings, name='receivings'),
    path('dispatches/', views.dispatches, name='dispatches'),
    path('dispatch/<int:product_id>/', views.dispatch, name='dispatch'),
    path('export_stock/', views.export_stock, name='export_stock'),
    path('p_promotion/', views.product_promotion, name='p_promotion'),
    path('p_promotion/<int:product_id>/', views.promotion, name='promotion'),
    path('promotions/', views.promotions, name='promotions'),
    path('edit_promotion/<int:promotion_id>/',
         views.edit_promotion, name='edit_promotion'),
    path('delete_promotion/<int:promotion_id>/',
         views.delete_promotion, name='delete_promotion'),
    path('stock_update/<int:stocktake_id>/',
         views.stock_update, name='stock_update'),
      path('delete_stock_take/<int:stock_take_id>/',
         views.delete_stock_take, name='delete_stock_take'),
    path('supplier/edit/<int:pk>/', views.supplier_edit, name='supplier_edit'),
    path('supplier/delete/<int:pk>/',
         views.supplier_delete, name='supplier_delete'),
    path('products/d_product', views.d_product, name='d_product'),
      path('products/brands', views.brands, name='brands'),



]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.custom_login, name='login'),
    path('profile/<username>', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path("staffs", views.staffs, name="staffs"),
    path('delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path("not_allowed", views.not_allowed, name="not_allowed"),
    path('update/<int:user_id>/', views.update_user, name='update_staff'),

]

pos/models.py
from django.db import models

class Notification(models.Model):
    receiver = models.CharField(max_length=255)
    cc = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"Notification to {self.receiver}"

    class Meta:
        verbose_name = "Notification"
        verbose_name_plural = "Notifications"

product/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import *
from django.contrib.auth import get_user_model
from django.utils import timezone
from users.models import *

from django.db import models
from django.db.models import Q, UniqueConstraint


class Product(models.Model):
    product_code = models.CharField(max_length=50, unique=True, null=True)
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    min_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)
    image = models.ImageField(
        upload_to='products/', null=True, blank=True, default='default/user.jpg')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=0)
    units = models.CharField(max_length=50, null=True)
    brand = models.CharField(max_length=50, null=True)
    expiry_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        constraints = [
            UniqueConstraint(
                fields=['product_code'],
                condition=Q(product_code__isnull=False),
                name='unique_product_code'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Promotion(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name='promotion')
    initial_price = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()
    current_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)
    discount_percentage = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"Promotion for {self.product.title}"

    class Meta:
        verbose_name = 'Promotion'
        verbose_name_plural = 'Promotions'


class About(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'About'


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    contact_person = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, related_name='supplier', blank=True, null=True)
    products = models.ManyToManyField(
        Product, related_name='suppliers', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Buyer(models.Model):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    points = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name_plural = "Buyers"


class Cart(models.Model):
    # Use the custom user model
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    total_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    add_vat = models.BooleanField(default=False)  # Add this field
    total_payable = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    buyer = models.ForeignKey(
        Buyer, on_delete=models.SET_NULL, null=True, blank=True)  # Add buyer field
    points = models.IntegerField(null=True, blank=True)
    discount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.user:
            self.user_name = self.user.username


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(null=True)


class Sale(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    products_sold = models.ManyToManyField(Product, through='SaleItem')
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    discount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    vat = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    total_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    sale_date = models.DateTimeField(default=timezone.now)
    buyer = models.ForeignKey(
        Buyer, on_delete=models.SET_NULL, null=True, blank=True)
    cashed_up = models.BooleanField(default=False)

    def __str__(self):
        return f"Sale by {self.user.username}"


class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_sold = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.title


class Year(models.Model):
    year = models.PositiveIntegerField(unique=True)
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return str(self.year)


class Month(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    month = models.PositiveIntegerField()
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"{self.month} {self.year}"


class Week(models.Model):
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    week_number = models.PositiveIntegerField()
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"Week {self.week_number}, {self.month}"


class Day(models.Model):
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    day_of_week = models.CharField(max_length=10)
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    sales = models.ManyToManyField(Sale)
    date = models.DateField(null=True)

    def __str__(self):
        return self.day_of_week


class StockTake(models.Model):
    stock_date = models.DateField(default=timezone.now)
    products = models.ManyToManyField(Product, through='StockTakeItem')
    stock_value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    value = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    difference = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    stock_balanced = models.BooleanField(default=False)

    def __str__(self):
        return f"Stock Take on {self.stock_date} by {self.user}"


class StockTakeItem(models.Model):
    stock_take = models.ForeignKey(StockTake, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_counted = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.product}"


class PaymentMethod(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Payment(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment of {self.amount_paid} on {self.payment_date}"


class Receiving(models.Model):
    receiver = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    received_date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Receiving #{self.id} - {self.received_date}"


class ReceivedProduct(models.Model):
    receiving = models.ForeignKey(Receiving, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate total_amount before saving
        self.total_amount = self.product_quantity * self.unit_price
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product.title} - {self.product_quantity} units"

    class Meta:
        unique_together = ('receiving', 'product')


class Supply(models.Model):
    supplier = models.ForeignKey('Supplier', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)

pos/forms.py
from product.models import *
from django import forms
from .models import *


class AddToCartForm(forms.Form):
    product_id = forms.IntegerField(
        widget=forms.HiddenInput(attrs={'class': 'form-control'}))
    quantity = forms.IntegerField(
        min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control'}))


class NotificationForm(forms.ModelForm):
    class Meta:
        model = Notification
        fields = ['receiver', 'cc']


class CashupForm(forms.ModelForm):
    class Meta:
        model = Cashup
        fields = ['total_sales', 'expenses', 'cash_at_hand']
        widgets = {
            'total_sales': forms.NumberInput(attrs={'class': 'form-control'}),
            'expenses': forms.NumberInput(attrs={'class': 'form-control'}),
            'cash_at_hand': forms.NumberInput(attrs={'class': 'form-control'}),
        }

pos/templates/pos/add_to_cart.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row mb-4">
            <div class="col-md-6">
                <h2>Add to Cart</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add to Cart</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

pos/templates/pos/cart.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container">
        {% if cart %}
        <div class="row">
            <div class="col-lg-8">
               
                    <div class="card">
                        <div class="card-header">
                            Cart ({{ count }})
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">Cart Items</h4>
                            
                            <!-- Iterate over cart items -->
                            {% for item in cart %}
                                <div class="row mb-3">
                                    <!-- Product Image Column (4 cols) -->
                                    <div class="col-md-2">
                                        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="img-fluid" width="100" height="100">
                                    </div>
                                    
                                    <!-- Product Name and Quantity Column (6 cols) -->
                                    <div class="col-md-6">
                                        <h5>{{ item.product.title }}</h5>
                                        <p>Products Remaining: {{ item.product.quantity }}</p>
                                    </div>
                                    
                                    <!-- Product Price Column (2 cols) -->
                                    <div class="col-md-4 text-right">
                                        <p>Ksh  {{ item.product.price }}</p>
                                    </div>
                                </div>
                                <div class="row text-center mb-3">
                                    <div class="col-md-6">
                                        <a href="{% url 'pos:remove_cart_item' item.id %}" class="btn btn-primary waves-effect waves-light">Remove</a>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
                                            <a href="{% url 'pos:decrement_cart_item' item.id %}" class="btn btn-primary waves-effect waves-light"> - </a>
                                            <button type="button" class="btn btn-primary waves-effect">{{ item.quantity }}</button>
                                            <a href="{% url 'pos:increment_cart_item' item.id %}" class="btn btn-primary waves-effect waves-light"> + </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- End Iteration -->
                          
                        </div>
                    </div>
            </div>
            
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-header">
                        Cart Summary
                    </div>
                    <div class="card-body">
                       <div class="row">
                        <div class="col-md-6">
                            <b>Subtotal</b>
                        </div>
                        <div class="col-md-6">
                            <b> Ksh {{ total }}</b>
                        </div>
                       </div>
                    </div>
                    <div class="card-footer text-center">
                        <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target="#checkoutModal">
                            Checkout (Ksh  {{ total }})
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row justify-content-center text-center">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <i class="fas fa-shopping-cart text-warning fa-5x mb-3"></i>
                      <h1>  Nothing added to the basket to sell !!</h1>
                      <p>Browse Categories to add items to the basket</p>
                        <a href="{% url 'pos:index' %}" class="btn btn-primary">Browse Products</a>
                    </div>
                </div>
            </div>
        </div>
        
    {% endif %}
    </div>
</div>

<!-- Checkout Modal -->
<div class="modal fade" id="checkoutModal" tabindex="-1" role="dialog" aria-labelledby="checkoutModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <!-- Centered row for icon -->
                <div class="row justify-content-center">
                    <div class="col-12">
                        <i class="fas fa-exclamation-circle fa-5x text-danger"></i>
                    </div>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to Complete a Sale of  <b>ksh  {{ total }}</b>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a href="{% url 'pos:checkout'%}" class="btn btn-primary">Confirm</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

pos/templates/pos/cataloque.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<style>
    .card {
        height: 100%;
    }

    .card-body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
    }
</style>

<div class="page-content">
    <div class="container">
        <div class="row">
            {% if cat %}
            {% for c in cat %}

            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:cataloque_detail' c.id %}">
                 <div class="card">
                     <div class="card-body">
                         <h5 class="card-title">{{ c.name }}</h5>
                         <p>{{c.total_products}} Products</p>
                     </div>
                 </div>
                </a>
             </div>

            {%endfor%}
            {% else %}
            <h2>No Cataloque Available</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

pos/templates/pos/menu.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<style>
    .card {
        height: 100%;
    }

    .card-body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
    }
</style>

<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-md-3 mb-4">
               <a href="{% url 'product:products' %}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Products</h5>
                    </div>
                </div>
               </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'product:stock' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Stock</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
               <a href="{% url 'product:low_stock' %}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Low stock</h5>
                    </div>
                </div>
               </a>
            </div>
            <div class="col-md-3 mb-4">
              <a href="{% url 'product:out_of_stock' %}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Out of Stock</h5>
                    </div>
                </div>
              </a>
            </div>
            <div class="col-md-3 mb-4">
              <a href="{% url 'product:stock_movement' %}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Stock Movement</h5>
                    </div>
                </div>
              </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'product:stocks' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Stock Take</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:expiring' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Expiry</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
               <a href="{% url 'users:staffs' %}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Staffs</h5>
                    </div>
                </div>
               </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'product:suppliers' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Suppliers</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:received' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Receivings</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'product:dispatches' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Dispatch</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:supplies' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Cost</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'product:promotions' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Offers</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:about' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">About</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:cataloque' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Cataloque</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:mails' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Mails</h5>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 mb-4">
                <a href="{% url 'pos:cashups' %}">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">cashups</h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

pos/templates/pos/receipt.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-between">
                    <h4 class="mb-0 font-size-18">Receipt</h4>

                </div>
            </div>
        </div>  

        <div class="row">
            <embed src="{{ pdf_data }}" width="100%" height="600px" type='application/pdf'>
        </div>
        
    </div>
</div>
{% endblock content %}