eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('product.urls', namespace='product')),
     path('pos/', include('pos.urls', namespace='pos')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from . import views


app_name = 'pos'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/increment/<int:item_id>/',
         views.increment_cart_item, name='increment_cart_item'),
    path('cart/decrement/<int:item_id>/',
         views.decrement_cart_item, name='decrement_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart_item/<int:item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('sales/', views.sales, name='sales'),
    path('sale/<int:sale_id>/', views.sale, name='sale'),
    path('sales_h/', views.sales_h, name='sales_h'),
    path('toggle_vat/', views.toggle_add_vat, name='toggle_vat'),
    path('update_discount/', views.update_discount, name='update_discount'),
    path('eshop/inventory/', views.menu, name='menu'),
    path('eshop/expiring/', views.expiring, name='expiring'),
    path('eshop/receivings/', views.receivings, name='received'),
    path('eshop/supplies/', views.supplies, name='supplies'),
    path('eshop/about/', views.about, name='about'),
    path('eshop/cataloque/', views.cataloque, name='cataloque'),
    path('cataloque/<int:cataloque_id>/',
         views.cataloque_detail, name='cataloque_detail'),
    path('export_cataloque/<int:cataloque_id>/',
         views.export_cataloque, name='export_cataloque'),
    path('eshop/mails/', views.mails, name='mails'),
    path('eshop/create_mails/', views.create_mail, name='create_mails'),
    path('eshop/cashup/', views.cashup, name='cashup'),
    path('eshop/cashups/', views.cashups, name='cashups'),
    path('cashup/<int:cashup_id>/',
         views.cashup_detail, name='cashup_detail'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('create_product/', views.create_product, name='create_product'),
    path('create_category/', views.create_category, name='create_category'),
    path('products/', views.products, name='products'),
    path('edit_category/<int:category_id>/',
         views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/',
         views.delete_category, name='delete_category'),
    path('edit_product/<int:product_id>/',
         views.edit_product, name='edit_product'),
    # Delete Product
    path('delete_product/<int:product_id>/',
         views.delete_product, name='delete_product'),
    path('stock/', views.stock, name='stock'),
    path('low_stock/', views.low_stock, name='low_stock'),
    path('out_of_stock/', views.out_of_stock, name='out_of_stock'),
    path('create_stock_take/', views.create_stock_take, name='create_stock_take'),
    path('stocks/', views.stocks, name='stocks'),
    path('stock_detail/<int:stock_take_id>/',
         views.stock_detail, name='stock_detail'),
    path('stock_take/<int:stock_take_id>/update/<int:stock_take_item_id>/',
         views.update_stock_take_item, name='update_stock'),
    path('stockmovement/', views.stock_movement, name='stock_movement'),
    path('suppliers/', views.suppliers, name='suppliers'),
    path('supplier_create/', views.supplier_create, name='supplier_create'),
    path('receivings/', views.receivings, name='receivings'),
    path('dispatches/', views.dispatches, name='dispatches'),
    path('dispatch/<int:product_id>/', views.dispatch, name='dispatch'),
    path('export_stock/', views.export_stock, name='export_stock'),
    path('p_promotion/', views.product_promotion, name='p_promotion'),
    path('p_promotion/<int:product_id>/', views.promotion, name='promotion'),
    path('promotions/', views.promotions, name='promotions'),
    path('edit_promotion/<int:promotion_id>/',
         views.edit_promotion, name='edit_promotion'),
    path('delete_promotion/<int:promotion_id>/',
         views.delete_promotion, name='delete_promotion'),
    path('stock_update/<int:stocktake_id>/',
         views.stock_update, name='stock_update'),
      path('delete_stock_take/<int:stock_take_id>/',
         views.delete_stock_take, name='delete_stock_take'),
    path('supplier/edit/<int:pk>/', views.supplier_edit, name='supplier_edit'),
    path('supplier/delete/<int:pk>/',
         views.supplier_delete, name='supplier_delete'),
    path('products/d_product', views.d_product, name='d_product'),
      path('products/brands', views.brands, name='brands'),



]

product/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import *
from django.contrib.auth import get_user_model
from django.utils import timezone
from users.models import *

from django.db import models
from django.db.models import Q, UniqueConstraint


class Product(models.Model):
    product_code = models.CharField(max_length=50, unique=True, null=True)
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    min_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)
    image = models.ImageField(
        upload_to='products/', null=True, blank=True, default='default/user.jpg')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=0)
    units = models.CharField(max_length=50, null=True)
    brand = models.CharField(max_length=50, null=True)
    expiry_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        constraints = [
            UniqueConstraint(
                fields=['product_code'],
                condition=Q(product_code__isnull=False),
                name='unique_product_code'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Promotion(models.Model):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name='promotion')
    initial_price = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    end_date = models.DateField()
    current_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)
    discount_percentage = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"Promotion for {self.product.title}"

    class Meta:
        verbose_name = 'Promotion'
        verbose_name_plural = 'Promotions'


class About(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'About'


class Supplier(models.Model):
    name = models.CharField(max_length=100)
    contact_person = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, related_name='supplier', blank=True, null=True)
    products = models.ManyToManyField(
        Product, related_name='suppliers', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Buyer(models.Model):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    points = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name_plural = "Buyers"


class Cart(models.Model):
    # Use the custom user model
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')
    total_cost = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    add_vat = models.BooleanField(default=False)  # Add this field
    total_payable = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)
    buyer = models.ForeignKey(
        Buyer, on_delete=models.SET_NULL, null=True, blank=True)  # Add buyer field
    points = models.IntegerField(null=True, blank=True)
    discount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.user:
            self.user_name = self.user.username


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(null=True)


class Sale(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    products_sold = models.ManyToManyField(Product, through='SaleItem')
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    discount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    vat = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    total_paid = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    sale_date = models.DateTimeField(default=timezone.now)
    buyer = models.ForeignKey(
        Buyer, on_delete=models.SET_NULL, null=True, blank=True)
    cashed_up = models.BooleanField(default=False)

    def __str__(self):
        return f"Sale by {self.user.username}"


class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_sold = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.title


class Year(models.Model):
    year = models.PositiveIntegerField(unique=True)
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return str(self.year)


class Month(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    month = models.PositiveIntegerField()
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"{self.month} {self.year}"


class Week(models.Model):
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    week_number = models.PositiveIntegerField()
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"Week {self.week_number}, {self.month}"


class Day(models.Model):
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    day_of_week = models.CharField(max_length=10)
    sales_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    sales = models.ManyToManyField(Sale)
    date = models.DateField(null=True)

    def __str__(self):
        return self.day_of_week


class StockTake(models.Model):
    stock_date = models.DateField(default=timezone.now)
    products = models.ManyToManyField(Product, through='StockTakeItem')
    stock_value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    value = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    difference = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    stock_balanced = models.BooleanField(default=False)

    def __str__(self):
        return f"Stock Take on {self.stock_date} by {self.user}"


class StockTakeItem(models.Model):
    stock_take = models.ForeignKey(StockTake, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity_counted = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.product}"


class PaymentMethod(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Payment(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment of {self.amount_paid} on {self.payment_date}"


class Receiving(models.Model):
    receiver = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    received_date = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Receiving #{self.id} - {self.received_date}"


class ReceivedProduct(models.Model):
    receiving = models.ForeignKey(Receiving, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(
        max_digits=12, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate total_amount before saving
        self.total_amount = self.product_quantity * self.unit_price
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product.title} - {self.product_quantity} units"

    class Meta:
        unique_together = ('receiving', 'product')


class Supply(models.Model):
    supplier = models.ForeignKey('Supplier', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)

product/templates/product/create_category.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                    <div class="card-body">
                        <h2 class="card-title text-center">Add New Product Category</h2>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.name.id_for_label }}">Category Name</label>
                                {{ form.name }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Add Product Category</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

product/templates/product/products.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid-lg">
       <div class="card">
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-md-3 text-center">
                    <a href="{% url 'product:create_category' %}" class="btn btn-primary">Add Product Category</a>
                </div>
                <div class="col-md-6 text-center">
                    <form method="GET" class="mb-3 ml-2">
                        <div class="input-group">
                            <input type="text" name="title" class="form-control form-control-lg" placeholder="Search Product Name">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                           
                        </div>
                    </form>
    
                    {% if request.GET.title %}
                  
                            <a href="{% url 'product:products' %}" class="btn btn-primary">Show All</a>
                      
                    {% endif %}
    
                </div>
                <div class="col-md-3 text-center">
                    <a href="{% url 'product:create_product' %}" class="btn btn-primary">Add New Product</a>
                </div>
            </div>
        </div>
       </div>
        
        <div class="row">
            <div class="col-md-3">
               <div class="card">
                <div class="card-body">
                     <!-- Display Categories -->
                <h5 class="card-title"><b>Categories</b></h5>
                <ul class="list-group mb-4">
                    {% for category in categories %}
                    <li class="list-group-item">
                        <a href="{% url 'product:products' %}?category={{ category.id }}">{{ category.name }}</a>
                        <span class="float-right">
                            <a href="{% url 'product:edit_category' category.id %}">Edit</a> |
                            <a href="{% url 'product:delete_category' category.id %}">Delete</a>
                        </span>
                    </li>
                {% empty %}
                    <li class="list-group-item">No Categories Available</li>
                {% endfor %}
                </ul>
                </div>
               </div>
                
            </div>
            <div class="col-md-9">
           <div class="card">
            <div class="card-body">
                
                <div class="row">
                    {% for product in products %}
                    <div class="col-md-4 mb-3">
                        <div class="card border-0">
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" style="height: 168px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.title }}</h5>
                                {% if product.brand %}
                                <p class="card-text">Brand: {{ product.brand }}</p>
                                {% endif %}
                                <!-- Display Units if not null -->
                                {% if product.units %}
                                <p class="card-text">Units: {{ product.units }}</p>
                                {% endif %}
                                <p class="card-text">Price: Ksh {{ product.price }}</p>
                                <p class="card-text">Quantity: {{ product.quantity }}</p>
                                <!-- Add more fields as needed -->
                
                                <!-- Edit Product Link -->
                                <a href="{% url 'product:edit_product' product.id %}" class="btn btn-primary">Edit</a>
                                <!-- Delete Product Link -->
                                <a href="{% url 'product:delete_product' product.id %}" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 and not forloop.last %}
                        </div><div class="row">
                    {% endif %}
                {% empty %}
                    <div class="col-12 text-center">
                        <p>No Products available</p>
                    </div>
                {% endfor %}
                
                </div>
                <!-- Pagination Links -->
                <div class="col-12 text-center">
                    <ul class="pagination">
                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">First</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                            </li>
                        {% endif %}
                        <li class="page-item disabled">
                            <span class="page-link">Page {{ products.number }} of {{ products.paginator.num_pages }}</span>
                        </li>
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.paginator.num_pages }}">Last</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <!-- End of Pagination Links -->
            </div>
           </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock content %}

product/templates/product/promotions.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
           
                <div class="row">
                    {% for p in promo %}
                    <div class="col-md-4 mb-3">
                        <div class="card position-relative">
                            <!-- Discount Badge -->
                            {% if p.discount_percentage %}
                            <span class="badge badge-danger position-absolute top-0 end-0">{{ p.discount_percentage }}% OFF</span>
                            {% endif %}

                            <img src="{{ p.product.image.url }}" class="card-img-top" alt="{{ p.product.name }}" style="height: 168px; object-fit: cover;">
                            <div class="card-body">
                                <h5 class="card-title">{{ p.product.title }}</h5>
                                {% if p.product.brand %}
                                <p class="card-text">Brand: {{ p.product.brand }}</p>
                                {% endif %}
                                
                                {% if p.product.units %}
                                <p class="card-text">Units: {{ p.product.units }}</p>
                                {% endif %}
                                {%if p.initial_price%}
                                <p class="card-text">Before: Ksh <del>{{ p.initial_price }}</del></p>
                                {%endif%}
                                <p class="card-text">Now: Ksh {{ p.product.price }}</p>
                                <p class="card-text">Remaining: {{ p.product.quantity }}</p>
                                <i><p class="card-text">Duration: {{ p.start_date }} - {{p.end_date}}</p></i>
                              
                                <a href="{% url 'product:edit_promotion' p.id %}" class="btn btn-primary">Edit</a>

                               
                                <a href="{% url 'product:delete_promotion' p.id %}" class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 and not forloop.last %}
                        </div><div class="row">
                    {% endif %}
                {% empty %}
                    <div class="col-12 text-center">
                        <p>No Products available</p>
                    </div>
                {% endfor %}
                
                </div>
                <div class="col-12 text-center">
                    <a href="{% url 'product:p_promotion' %}" class="btn btn-primary">Create New Promotion</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

product/templates/product/stocks.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid-lg">
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-flex align-items-center justify-content-center">
                    <h4 class="mb-0 font-size-18" style="color: #F5772B;">Stock Take History</h4>

                    
                </div>
            </div>
        </div>  
        
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body alert-info">
                        <h4 class="card-title mb-4 text-center" style="color: #F5772B;">Select / Create stock to take action</h4>
                        
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Stock Date</th>
                                        <th>Stock taken by</th>
                                        <th>Products Counted</th>
                                        <th>Stock status</th>
                                        <th>Stock Value</th>
                                        <th>Counted Value</th>
                                        <th>Difference</th>
                                        <th>Update Counts</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if stocks %}
                                        {% for stock in stocks %}
                                        <tr>
                                            <td>{{ stock.id }}</td>
                                            <td>{{ stock.stock_date }}</td>
                                            <td>{{ stock.user }}</td>
                                            <td>{{ stock.stocktakeitem_set.count }}</td>
                                            <td>
                                                {% if stock.stock_balanced %}
                                                <p class="text-success">Balanced</p>
                                                {%else%}
                                                <p class="text-danger">Negative</p>
                                                {% endif %}
                                            </td>
                                            <td class="text-success">{{ stock.stock_value }}</td>
                                            <td>
                                                {% if stock.balanced%}
                                                <p class="text-success">{{ stock.value }}</p>
                                                {%else%}
                                                <p class="text-danger">{{ stock.value }}</p>
                                                {%endif%}
                                            </td>
                                            <td>
                                                {% if stock.balanced %}
                                                <p class="text-success">{{ stock.difference }}</p>
                                                {% else %}
                                                <p class="text-danger">{{ stock.difference }}</p>
                                                {% endif %}
                                            </td>
                                            <td><a href="{% url 'product:stock_detail' stock.id %}">Update counts</a></td>
                                            <td>
                                               
                                                {% if user.is_authenticated and user.access_level == 1 %}
                                                <a href="#" onclick="confirmUpdate()" class="btn btn-primary">Submit Stock</a>
                                                <a href="#" onclick="confirmDelete()" class="btn btn-danger ml-2">Delete</a>
                                            {% endif %}
                                            
                                            </td>
                                        </tr>
                                        <script>
                                            function confirmUpdate() {
                                                var result = confirm("Are you sure you want to Submit the stock?");
                                                if (result) {
                                                    window.location.href = "{% url 'product:stock_update' stock.id %}";
                                                } 
                                            }
                                        </script>
                                        <script>
                                            function confirmDelete() {
                                                var result = confirm("Are you sure you want to Delete this Stock Take ?");
                                                if (result) {
                                                    window.location.href = "{% url 'product:delete_stock_take' stock.id %}";
                                                } 
                                            }
                                        </script>
                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td colspan="5">No stock taken yet</td>
                                        </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                            <div class="col-12 text-center">
                                <a href="{% url 'product:create_stock_take' %}" class="btn btn-primary">Create New Stock</a>
                            </div>
                             
                        </div>

                    </div>
                    <!-- end card-body-->
                </div>
                <!-- end card -->

            </div>
            <!-- end col -->


           
            <!-- end col -->
        </div>
        
    </div>
</div>

{% endblock content %}