eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('product.urls', namespace='product')),
     path('pos/', include('pos.urls', namespace='pos')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/urls.py
from django.urls import path
from . import views


app_name = 'pos'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/increment/<int:item_id>/',
         views.increment_cart_item, name='increment_cart_item'),
    path('cart/decrement/<int:item_id>/',
         views.decrement_cart_item, name='decrement_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart_item/<int:item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('sales/', views.sales, name='sales'),
    path('sale/<int:sale_id>/', views.sale, name='sale'),
    path('sales_h/', views.sales_h, name='sales_h'),
    path('toggle_vat/', views.toggle_add_vat, name='toggle_vat'),
    path('update_discount/', views.update_discount, name='update_discount'),
    path('eshop/inventory/', views.menu, name='menu'),
    path('eshop/expiring/', views.expiring, name='expiring'),
    path('eshop/receivings/', views.receivings, name='received'),
    path('eshop/supplies/', views.supplies, name='supplies'),
    path('eshop/about/', views.about, name='about'),
    path('eshop/cataloque/', views.cataloque, name='cataloque'),
    path('cataloque/<int:cataloque_id>/',
         views.cataloque_detail, name='cataloque_detail'),
    path('export_cataloque/<int:cataloque_id>/',
         views.export_cataloque, name='export_cataloque'),
    path('eshop/mails/', views.mails, name='mails'),
    path('eshop/create_mails/', views.create_mail, name='create_mails'),
    path('eshop/cashup/', views.cashup, name='cashup'),
    path('eshop/cashups/', views.cashups, name='cashups'),
    path('cashup/<int:cashup_id>/',
         views.cashup_detail, name='cashup_detail'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.custom_login, name='login'),
    path('profile/<username>', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path("staffs", views.staffs, name="staffs"),
    path('delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path("not_allowed", views.not_allowed, name="not_allowed"),
    path('update/<int:user_id>/', views.update_user, name='update_staff'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    ACCESS_LEVEL_CHOICES = (
        (1, 'Admin'),
        (2, 'Manager'),
        (3, 'Cashier'),
    )

    access_level = models.IntegerField(
        choices=ACCESS_LEVEL_CHOICES,
        null=True,
        blank=True
    )
    
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.username

main/forms.py
from django import forms
from .models import *

class HeroForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Hero
        fields = ['title', 'content', 'image']


class SeniorForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),
        label='Name'
    )

    profile_pic = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Profile Picture'
    )

    capacity = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter capacity'}),
        label='Capacity'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        label='Description'
    )

    class Meta:
        model = Senior
        fields = ['name', 'profile_pic', 'capacity', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make the profile_pic field not required
        self.fields['profile_pic'].required = False

class CompanyProfileForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),
        label='Name'
    )

    logo = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Logo'
    )

    banner_image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Banner Image'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        label='Description'
    )

    website = forms.URLField(
        max_length=200,
        widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Enter website URL'}),
        label='Website'
    )

    headquarters = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter headquarters'}),
        label='Headquarters'
    )

    vision = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter vision'}),
        label='Vision'
    )

    mission = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter mission'}),
        label='Mission'
    )

    class Meta:
        model = CompanyProfile
        fields = ['name', 'logo', 'banner_image', 'description', 'website', 'headquarters', 'vision', 'mission']


class EventForm(forms.ModelForm):
    company = forms.ModelChoiceField(
        queryset=CompanyProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select company'}),
        label='Associated Company'
    )

    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter event name'}),
        label='Event Name'
    )

    event_image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Event Image'
    )

    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date Started', 'type': 'date'}),
        label='Date Started', required=False
    )

    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Select end date', 'type': 'date'}),
        label='Event End Date'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter event description'}),
        label='Event Description'
    )

    location = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter event location'}),
        label='Event Location'
    )

    class Meta:
        model = Event
        fields = ['company', 'name', 'event_image', 'start_date', 'end_date', 'description', 'location']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.forms import PasswordResetForm
from .models import *
from django.contrib.auth.forms import UserChangeForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(
        help_text='A valid email address, please.', required=True)

    ACCESS_LEVEL_CHOICES = CustomUser.ACCESS_LEVEL_CHOICES

    access_level = forms.ChoiceField(
        choices=ACCESS_LEVEL_CHOICES,
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', 'access_level']

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

        # Add CSS classes to form fields
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'First Name'})
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Email Address'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm Password'})
        self.fields['access_level'].widget.attrs.update(
            {'class': 'form-control'})

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.access_level = self.cleaned_data['access_level']

        if commit:
            user.save()
        return user


class PortalManagementForm(UserCreationForm):
    email = forms.EmailField(
        help_text='A valid email address, please.', required=True)
    access_level = forms.ChoiceField(
        choices=CustomUser.ACCESS_LEVEL_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True,
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email',
                  'access_level', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(PortalManagementForm, self).__init__(
            *args, **kwargs)  # Use correct form class name

        # Add CSS classes to form fields
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Email Address'})
        self.fields['access_level'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Access Level'})
        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Confirm Password'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))


class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)


class UserUpdateForm(UserChangeForm):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput, required=False)
    is_active = forms.BooleanField(required=False)
    access_level = forms.ChoiceField(
        choices=get_user_model().ACCESS_LEVEL_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'password',
                  'confirm_password', 'access_level', 'is_active']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="#" style="width: 50; height: 50;" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-user-alt"></i>
                                        </a>
                                    </div>
                                    <h1 class="h5 mb-1 text-center">Welcome Back!</h1>
                                    <p class="text-muted mb-4 text-center">Enter your email address or username to Login</p>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Login</button>
                                            

                                        </div>
                                    </form>

                                    <div class="row mt-4">
                                        <div class="col-12 text-center">
                                            <p class="text-muted mb-2"><a href="{% url 'users:password_reset' %}" class="text-muted font-weight-medium ml-1">Forgot your password?</a></p>
                                            <p class="text-muted mb-2"><a href="{% url 'main:index' %}" class="text-muted font-weight-medium ml-1">Home</a></p>
                                        </div> <!-- end col -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
        {% block content %}

        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <h2>You have been logged out</h2>
                        <div class="border-top pt-3"  style="min-height:65vh;">
                            <small class="text-muted">
                                <a href="{% url 'login' %}">Log In Again</a>
                            </small>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>

         

        {% endblock content %}

      
   

users/templates/users/not_allowed.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <a href="#" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-ban fa-lg text-danger"></i>

                                        </a>
                                    </div>
                                    <h1 class="h5 mb-1 text-center">You do not have permission to perform this action.</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="#" style="width: 50; height: 50;" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-user-alt"></i>
                                        </a>
                                    </div>
                                    <h1 class="h5 mb-1 text-center">Recover Your Password</h1>
                                    <p class="text-muted mb-4 text-center">Enter your email address and we'll send you an email with instructions to reset your password.</p>
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Submit</button>
                                            

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="d-flex align-items-center min-vh-100 justify-content-center">
                    <div class="w-100 w-md-75 d-block bg-white shadow-lg rounded my-5">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center mb-5">
                                        <a href="#" style="width: 50; height: 50;" class="text-dark font-size-22 font-family-secondary">
                                            <i class="fas fa-user-alt"></i>
                                        </a>
                                    </div>
                                    <h1 class="h5 mb-1 text-center">Change Password</h1>
                                    
                                    <form method="POST">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Reset Password</button>
                                            

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
        {% block content %}

        <div class="page-content">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-8 justify-content-center">
                        <legend class="border-bottom mb-4">Profile Information:</legend>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="media">
                                <div class="form-group col-md-6 mb-0">
                                    {% if user.username == form.instance.username %}
                                    <input id="id_image" type="file" name="profile" hidden/>
                                        <label for="id_image">
                                                <img class="avatar-xl" 
                                                    style="cursor: pointer;" src="{{ form.instance.profile.url }}" title="Upload new image">
                                        </label>
                                {% else %}
                                        <img class="rounded-circle account-img profile-image" src="{{ form.instance.profile.url }}">
                                {% endif %}
                                </div>
                                <div class="form-group col-md-6 mb-0">
                                    <div class="media-body">
                                        <h2 class="account-heading">{{ form.instance.username }}
                                           
                                        </h2>
                                        <p class="text-secondary">{{ form.instance.first_name }} {{ form.instance.last_name }}</p>
                                        <p class="text-secondary">{{ form.instance.email }}</p>
                                       
                                    </div>
                                </div>
                            </div>
                        </div>

                        {% if user.username == form.instance.username %}
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Edit Profile Information</legend>
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        {{ form.first_name|as_crispy_field }}
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                        {{ form.last_name|as_crispy_field }}
                                    </div>
                                </div> 
                                {{ form.email|as_crispy_field }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Update</button>
                            </div>
                        {% endif %}
                    </form>
                    <div class="row mt-4">
                        <div class="col-12 text-center">
                            <p class="text-muted mb-0"><a href="{% url 'users:password_change' %}" class="text-muted font-weight-medium ml-1"><b>Change Password</b></a></p>
                        </div>
                    </div>
                    </div>
                </div>
            
            </div>
        </div>

         

        {% endblock content %}

      
   

users/templates/users/staffs.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                    <div class="card-body">
                        <h2 class="card-title text-center">Health Today staffs</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Username</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Access Rights</th>
                                        <th>Date Created</th>
                                        <th>Status</th> <!-- New column for status -->
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for staff in staffs %}
                                    <tr>
                                        <td>{{ staff.id }}</td>
                                        <td>{{ staff.username }}</td>
                                        <td>{{ staff.first_name }}</td>
                                        <td>{{ staff.last_name }}</td>
                                        <td>{{ staff.get_access_level_display }}</td>
                                        <td>{{ staff.date_created }}</td>
                                        <td>{% if staff.is_active %} Active {% else %} Inactive {% endif %}</td> <!-- Display active or inactive status -->
                                        <td>
                                            <a href="{% url 'users:update_staff' user_id=staff.id %}" class="btn btn-primary">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </a>
                                            <a href="{% url 'users:delete_user' user_id=staff.id %}" class="btn btn-danger ml-2">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="8">No staffs available</td> <!-- Adjust colspan for new column -->
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="col-12 text-center">
                            <a href="{% url 'users:register' %}" class="btn btn-primary btn-lg active">Add new staff</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/template_reset_password.html
{% autoescape off %}
Hello {{ user.username }},

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
Kengen Careers

{% endautoescape %}