eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('product.urls', namespace='product')),
     path('pos/', include('pos.urls', namespace='pos')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('buyers/', views.buyers, name='buyers'),
    path('create_buyer/', views.create_buyer, name='create_buyer'),
    path('print/', views.print_and_cut, name='print'),
    path('create_about/', views.create_about, name='create_about'),

]

pos/urls.py
from django.urls import path
from . import views


app_name = 'pos'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_cart/<int:product_id>/', views.add_to_cart, name='add_cart'),
    path('cart/', views.cart, name='cart'),
    path('cart/increment/<int:item_id>/',
         views.increment_cart_item, name='increment_cart_item'),
    path('cart/decrement/<int:item_id>/',
         views.decrement_cart_item, name='decrement_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('remove_cart_item/<int:item_id>/',
         views.remove_cart_item, name='remove_cart_item'),
    path('sales/', views.sales, name='sales'),
    path('sale/<int:sale_id>/', views.sale, name='sale'),
    path('sales_h/', views.sales_h, name='sales_h'),
    path('toggle_vat/', views.toggle_add_vat, name='toggle_vat'),
    path('update_discount/', views.update_discount, name='update_discount'),
    path('eshop/inventory/', views.menu, name='menu'),
    path('eshop/expiring/', views.expiring, name='expiring'),
    path('eshop/receivings/', views.receivings, name='received'),
    path('eshop/supplies/', views.supplies, name='supplies'),
    path('eshop/about/', views.about, name='about'),
    path('eshop/cataloque/', views.cataloque, name='cataloque'),
    path('cataloque/<int:cataloque_id>/',
         views.cataloque_detail, name='cataloque_detail'),
    path('export_cataloque/<int:cataloque_id>/',
         views.export_cataloque, name='export_cataloque'),
    path('eshop/mails/', views.mails, name='mails'),
    path('eshop/create_mails/', views.create_mail, name='create_mails'),
    path('eshop/cashup/', views.cashup, name='cashup'),
    path('eshop/cashups/', views.cashups, name='cashups'),
    path('cashup/<int:cashup_id>/',
         views.cashup_detail, name='cashup_detail'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'
urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.custom_login, name='login'),
    path('profile/<username>', views.profile, name='profile'),
    path('logout', views.custom_logout, name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm,
         name='password_reset_confirm'),
    path("not_authorized/", views.not_authorized, name="not_authorized"),
    path("staffs", views.staffs, name="staffs"),
    path('delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path("not_allowed", views.not_allowed, name="not_allowed"),
    path('update/<int:user_id>/', views.update_user, name='update_staff'),

]

main/models.py
from django.db import models

# Create your models here.

class Hero(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='hero_images/', default='default/sm-3.jpg')

    def __str__(self):
        return self.title
    
class Senior(models.Model):
    name = models.CharField(max_length=255)
    profile_pic = models.ImageField(upload_to='seniors/', default='default/user.jpg')
    capacity = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
    

class CompanyProfile(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='company_logos/', default='default/default_logo.png')
    banner_image = models.ImageField(upload_to='company_banners/', default='default/default_banner.jpg')
    description = models.TextField()
    website = models.URLField(max_length=200)
    headquarters = models.CharField(max_length=255)
    vision = models.TextField()
    mission = models.TextField()
    # Add any additional fields you need

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=255)
    event_image = models.ImageField(upload_to='event_images/', default='default/event.png')
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()
    location = models.CharField(max_length=255)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    # Add any additional fields you need for events

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import *

class HeroForm(forms.ModelForm):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    image = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Hero
        fields = ['title', 'content', 'image']


class SeniorForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),
        label='Name'
    )

    profile_pic = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Profile Picture'
    )

    capacity = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter capacity'}),
        label='Capacity'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        label='Description'
    )

    class Meta:
        model = Senior
        fields = ['name', 'profile_pic', 'capacity', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make the profile_pic field not required
        self.fields['profile_pic'].required = False

class CompanyProfileForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),
        label='Name'
    )

    logo = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Logo'
    )

    banner_image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Banner Image'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        label='Description'
    )

    website = forms.URLField(
        max_length=200,
        widget=forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Enter website URL'}),
        label='Website'
    )

    headquarters = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter headquarters'}),
        label='Headquarters'
    )

    vision = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter vision'}),
        label='Vision'
    )

    mission = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter mission'}),
        label='Mission'
    )

    class Meta:
        model = CompanyProfile
        fields = ['name', 'logo', 'banner_image', 'description', 'website', 'headquarters', 'vision', 'mission']


class EventForm(forms.ModelForm):
    company = forms.ModelChoiceField(
        queryset=CompanyProfile.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select company'}),
        label='Associated Company'
    )

    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter event name'}),
        label='Event Name'
    )

    event_image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        label='Event Image'
    )

    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date Started', 'type': 'date'}),
        label='Date Started', required=False
    )

    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Select end date', 'type': 'date'}),
        label='Event End Date'
    )

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter event description'}),
        label='Event Description'
    )

    location = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter event location'}),
        label='Event Location'
    )

    class Meta:
        model = Event
        fields = ['company', 'name', 'event_image', 'start_date', 'end_date', 'description', 'location']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.contrib import messages
from product.forms import *
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required


def is_superuser_admin_cashier(user):
    return user.is_superuser or (user.access_level in [1, 3])


def index(request):
    categories = Category.objects.all()

    # Retrieve all products
    products_list = Product.objects.all()

    title_filter = request.GET.get('title')

    category_id = request.GET.get('category')
    if category_id:
        selected_category = get_object_or_404(Category, id=category_id)
        products_list = products_list.filter(category=selected_category)
    else:
        selected_category = None

    if title_filter:
        products_list = products_list.filter(title__icontains=title_filter)

    paginator = Paginator(products_list, 9)
    page_number = request.GET.get('page')

    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    # Prefetch related products for each category to avoid multiple database queries
    categories_with_products = []
    for category in categories:
        category_products = products_list.filter(category=category)
        categories_with_products.append(
            {'category': category, 'products': category_products})

    slider1 = Promotion.objects.all()
    slider2 = Product.objects.order_by('-price')[:5]
    about = About.objects.all()
    available_products = Product.objects.filter(quantity__gt=0)

    context = {
        'categories': categories,
        'products': products,
        's1': slider1,
        's2': slider2,
        'selected_category': selected_category,
        'about': about,
        'ap': available_products,
        'categories_with_products': categories_with_products,  # Add this to context
    }

    return render(request, 'main/index.html', context)


def product_detail(request, product_id):
    # Retrieve product object or return 404 error if not found
    product = get_object_or_404(Product, pk=product_id)

    # Retrieve the category of the product
    category = product.category

    # Retrieve other products in the same category excluding the current product
    other_products = Product.objects.filter(
        category=category).exclude(pk=product_id)

    print(other_products)

    # Render template with product details and other products in the same category
    return render(request, 'main/product_detail.html', {'product': product, 'other_products': other_products})


@login_required
@user_passes_test(is_superuser_admin_cashier, login_url='users:not_authorized')
def create_buyer(request):
    if request.method == 'POST':
        form = BuyerForm(request.POST)
        if form.is_valid():
            # Create a new Buyer instance and save it to the database
            buyer = form.save()
            # Replace 'buyer_list' with the URL name for listing buyers
            return redirect('main:buyers')
    else:
        form = BuyerForm()

    context = {
        'form': form,
    }

    return render(request, 'main/create_buyer.html', context)


@login_required
@user_passes_test(is_superuser_admin_cashier, login_url='users:not_authorized')
def buyers(request):
    buyers = Buyer.objects.all()

    context = {
        'buyers': buyers,
    }

    return render(request, 'main/buyers.html', context)


def print_and_cut(request):
    return render(request, 'main/receipt.html')


def create_about(request):
    if request.method == 'POST':
        form = AboutForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to a success page or do something else
            return redirect('pos:about')
    else:
        form = AboutForm()

    return render(request, 'main/create_about.html', {'form': form})

main/templates/main/includes/footer.html
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-center text-lg-left">
                                 
                    <div id="footerText" class="text-center text-lg-left">
                        <!-- Content will be inserted here dynamically -->
                    </div>
                    
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="text-right d-none d-lg-block">
                                    Health Today
                                </div>
                            </div>
                        </div>
                    </div>
               

main/templates/main/includes/hero.html
{% load static %}
<!-- Carousel Section -->
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
        <!-- Slide 1 -->
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="{% static 'dashboard/images/media/Aef001.jpg' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <!-- <h3 class="text-white">Employment Opportunities</h3>
                <p>You want to grow your career with KenGen?</p>
                <a href="{% url 'vacancies:jobs' %}" class="btn btn-primary btn-rounded waves-effect waves-light">
                    Explore Open Jobs
                </a> -->
            </div>
        </div>
        <!-- Slide 2 -->
        <div class="carousel-item">
            <img class="d-block img-fluid" src="{% static 'dashboard/images/media/Aef002.jpg' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <!-- <h3 class="text-white">Internship opportunities</h3>
                <p>Are you looking for internship opportunity with us?</p>
                <a href="{% url 'vacancies:internships' %}" class="btn btn-primary btn-rounded waves-effect waves-light">
                    Explore Open Internships
                </a> -->
            </div>
        </div>
        <!-- Slide 3 -->
        <div class="carousel-item">
            <img class="d-block img-fluid" src="{% static 'dashboard/images/media/Aef003.jpg' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <!-- <h3 class="text-white">Industrial attachments</h3>
                <p>You wish to relate theory to market realities?</p>
                <a href="{% url 'vacancies:attachments' %}" class="btn btn-primary btn-rounded waves-effect waves-light">
                    Explore Open Attachments
                </a> -->
            </div>
        </div>
    </div>
    <!-- Carousel Controls -->
    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

main/templates/main/includes/messaging.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
{% load static %}



<div class="topnav">
    <div class="container text-center">
        <nav class="navbar navbar-light navbar-expand-lg">
            <div class="mx-auto collapse navbar-collapse" id="topnav-menu-content" style="justify-content: center;">
                {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:index' %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pos:menu' %}">
                            Inventory
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pos:index' %}">
                            POS
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pos:sales' %}">
                            Today Sales
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pos:sales_h' %}">
                            Sales
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:buyers' %}">
                            Customers
                        </a>
                    </li>
                    <li class="nav-item d-lg-none">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <strong>{{ user.username }}</strong>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                <a href="{% url 'users:logout' %}" class="dropdown-item notify-item">
                                    <span class="align-middle">Logout</span>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
                {%else%}
                <div class="flashing-text text-white">
                    <h1 class="text-white">Call or Whatsapp to order <i class="fab fa-whatsapp">  </i> +254 794 085 329</h1>
                </div>
                
                
                {% endif %}
            </div>

           
            
        </nav>
    </div>
</div>